version: "3"

services:
  address_api:
    container_name: address_api
    image: address_api
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "3000:3000"
    environment:
      HTTP_SERVER_PORT: "3000"
      HTTP_CLIENT_TIMEOUT_MS: 60000
      CORREIOS_BASE_URL: https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl
      VIACEP_BASE_URL: https://viacep.com.br/ws/%s/json/