version: "3"

services:
  address_api:
    container_name: address_api
    image: address_api
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      HTTP_SERVER_PORT: "8000"
