application:
  replicas: 1
  image:
    name: "jailtonjunior/address-api"
    tag: "v2"
  configMap:
    server:
      port: "3000"
    httpTimeout: 60000
    correiosBaseURL: https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente?wsdl
    viaCepBaseURL: https://viacep.com.br/ws/%s/json/
  service:
    type: NodePort
  ingress:
    enable: false
