apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-address-api
spec:
  replicas: {{ .Values.application.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-address-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-address-api
    spec:
      containers:
        - name: address-api
          image: {{ .Values.application.image.name }}:{{ .Values.application.image.tag }}
          resources:
            limits:
              cpu: "50m"
              memory: "32Mi"
          envFrom:
            - configMapRef:
                name: address-config
          startupProbe:
            httpGet:
              path: /health
              port: {{ .Values.application.configMap.server.port }}
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.application.configMap.server.port }}
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.application.configMap.server.port }}
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 5
            successThreshold: 1
          ports:
            - containerPort: {{ .Values.application.configMap.server.port }}