name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_USERNAME: jailtonjunior

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (Address API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: deployment/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/address-api:latest
            ${{ env.DOCKER_USERNAME }}/address-api:v${{ github.run_number }}